name = "navigation-site"
main = "functions/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"
JWT_SECRET = "your-secret-key" # 在生产环境中应该使用更安全的密钥

[[kv_namespaces]]
binding = "NAVIGATION_KV"
id = "b097c512e3dc4870a1256e36d2d8d903"
preview_id = "your-preview-kv-namespace-id"

[site]
bucket = "./public"

# Pages配置
[pages]
pages_build_output_dir = "dist"
pages_build_command = "npm run build"
pages_include_files = ["public/**/*", "admin/**/*", "functions/**/*"]

# 路由配置
[[routes]]
pattern = "/admin/*"
zone_name = "navigation-site.your-domain.com"

# 安全配置
[security]
allowed_origins = ["https://navigation-site.your-domain.com"]
cors = true

# 缓存配置
[cache]
browser_ttl = 3600
edge_ttl = 3600

# 构建配置
[build]
command = "npm run build"
watch_dir = "src"

# 环境配置
[env.production]
name = "navigation-site-prod"
route = "your-domain.com/*"
zone_id = "your-zone-id"

[env.staging]
name = "navigation-site-staging"
route = "staging.your-domain.com/*"
zone_id = "your-zone-id"