name = "nav-site"
compatibility_date = "2024-01-01"

# Pages配置
[pages]
pages_build_output_dir = "."
functions = "functions"

# KV命名空间配置
kv_namespaces = [
  { binding = "KV", id = "dcf23728ee5149b39365cc46619037cc" }
]

[env.production]
# 生产环境变量
vars = { JWT_SECRET = "CHANGE_THIS_TO_A_SECURE_SECRET" }

[env.development]
# 开发环境变量
vars = { JWT_SECRET = "dev-secret" }